---
title: "ARPPU"
description: "Understand ARPPU (Average Revenue Per Paying User) and how it impacts your app’s monetization."
metadataTitle: "Understanding ARPPU Metrics | Adapty Docs"
---

import Zoom from 'react-medium-image-zoom';
import 'react-medium-image-zoom/dist/styles.css';

### ARPPU

The Average revenue per paying user (ARPPU) chart displays the average revenue per paid user. It displays the actual revenue generated by paying customers, divided by the number of customers, minus refunds.


<Zoom>
  <img src={require('./img/55cb433-small-CleanShot_2023-05-09_at_14.10.022x.webp').default}
  style={{
    border: '1px solid #727272', /* border width and color */
    width: '700px', /* image width */
    display: 'block', /* for alignment */
    margin: '0 auto' /* center alignment */
  }}
/>
</Zoom>





### Calculation

The ARPPU chart is calculated as:

ARPPU = Revenue / Number of users who paid

For example, if your app generated $10,000 in revenue over a given period and had 500 paying customers during that time, the ARPPU would be calculated as $10,000 / 500 = $20. This means that on average, each paying customer generated $20 in revenue during the selected period.

 It's important to note that the ARPPU value displayed represents the sum of total revenue divided by the total number of paying customers. The calculation is done before the store's fee and the refund amount is excluded from the revenue. As one user can pay more than one time during the whole period, the total ARPPU value may be higher than the daily value of ARPPU. This metric provides valuable insights into the revenue-generating capabilities of your app's paying user base and can help you optimize your pricing and subscription strategy to maximize revenue generation.

:::note
Refunds reduce the revenue component of this calculation, resulting in a lower ARPPU value. However, the user count in the denominator includes users whose purchases were later refunded, which can further decrease the average. This metric shows the true average revenue after accounting for refunds.
:::

### Available filters and grouping

- ✅ Filter by: Attribution, country, paywall, store, product, and duration. 
- ✅ Group by: Renewal status, period, product, country, store, paywall, duration, attribution status, attribution channel, attribution campaign, attribution ad group, attribution ad set, and attribution creative. 

You can find more information about the available controls, filters, grouping options, tax and commission controls, and how to use them in [this documentation.](controls-filters-grouping-compare-proceeds)

### ARPPU chart usage

The ARPPU chart in Adapty is a powerful tool that can help businesses understand the revenue generated by each paying user. By analyzing this metric over time, businesses can identify which channels, networks, and campaigns attract the most valuable customers. This information can be used to optimize marketing strategies and increase revenue by targeting high-value customers. With Adapty's ARPPU chart, businesses can make data-driven decisions that improve their bottom line and drive long-term success.

### Similar metrics

In addition to the ARPPU chart, Adapty also provides metrics for other revenue-related events, such as Revenue, MRR, ARR, and ARPU. To learn more about these revenue-related metrics, please refer to the following documentation guides:

- [Revenue](revenue)
- [MRR](mrr)
- [ARPU](arpu)
- [ARR](arr)