---
title: "Metrics in Adapty UA"
description: "Learn about the metrics available in Adapty UA."
metadataTitle: "Using Adapty User Acquisition | Adapty Docs"
keywords: ['adapty ua', 'user acquisition']
---

Adapty User Acquisition provides comprehensive **metrics** to measure campaign performance and user behavior. These metrics are available as standard values, with some metrics also offered as **cohort metrics** for time-based analysis of user groups.


| **Metric**                        | Description                                                                                                                                                                                                                                                                                                                                                                                                                                     | Cohort |
|-----------------------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|--------|
| **Spend**                         | The sum of the cost of each customer tap on your ad.                                                                                                                                                                                                                                                                                                                                                                                            | No     |
| **Impressions**                   | The number of times your ad was displayed within the selected period.                                                                                                                                                                                                                                                                                                                                                                           | No     |
| **Clicks**                        | The number of times users clicked on your ad within the reporting period.                                                                                                                                                                                                                                                                                                                                                                       | No     |
| **CPI**                           | **CPI (Cost per Install)** is the amount you pay for each install. <br/>**Formula**: `Spend / Installs`                                                                                                                                                                                                                                                                                                                                         | No     |
| **CPC**                           | **CPC (Cost per Click**) is the amount you pay for each click on your ad. <br/>**Formula**: `Spend / Clicks`                                                                                                                                                                                                                                                                                                                                    | No     |
| **CPM**                           | **CPM (Cost per Mille)** is the amount you pay per one thousand ad impressions. <br/>**Formula**: `Spend / (Impressions / 1000)`                                                                                                                                                                                                                                                                                                                | No     |
| **ICR**                           | **ICR (Install Conversion Rate)** is the percentage of ad clicks that resulted in installs. <br/>**Formula**: `(Installs / Clicks) × 100%`                                                                                                                                                                                                                                                                                                      | No     |
| **IPM**                           | **IPM (Installs per Mille)** represents the number of installs per one thousand ad impressions. <br/>**Formula**: `(Installs / Impressions) × 1000`                                                                                                                                                                                                                                                                                             | No     |
| **CTR**                           | **CTR (Click-Through Rate)** is the percentage of impressions that resulted in clicks. <br/>**Formula**: `(Clicks / Impressions) × 100%`                                                                                                                                                                                                                                                                                                        | No     |
| **Inline link clicks**            | The number of times users clicked inline links in your ad creatives or app page.                                                                                                                                                                                                                                                                                                                                                                | No     |
| **Cost per inline link click**    | The average amount you pay per inline link click. <br/>**Formula**: `Spend / Inline Link Clicks`                                                                                                                                                                                                                                                                                                                                                | No     |
| **Inline link click CTR**         | The percentage of impressions that resulted in inline link clicks. <br/>**Formula**: `(Inline Link Clicks / Impressions) × 100%`                                                                                                                                                                                                                                                                                                                | No     |
| **Installs**                      | The total number of users who installed your app (including re-installs) within the reporting period.                                                                                                                                                                                                                                                                                                                                           | No     |
| **Revenue**                       | The total amount of money generated from purchases linked to this campaign (before store commission) within the selected timeframe.                                                                                                                                                                                                                                                                                                             | Yes    |
| **ROAS**                          | **ROAS (Return on Ad Spend)** is the revenue from your ads divided by ad spend, expressed as a percentage. <br/> **Formula**: `(Revenue / Spend) × 100% if Spend > 0, otherwise 0% `                                                                                                                                                                                                                                                            | Yes    |
| **ARPU**                          | **ARPU (Average Revenue per User)** is the average revenue per user in the cohort. <br/>**Formula**: `Revenue / Users`                                                                                                                                                                                                                                                                                                                          | Yes    |
| **LTV**                           | **LTV (Lifetime Value)** is the average revenue attributed to a user over their lifetime. <br/>**Formula**: `Revenue / Installs`                                                                                                                                                                                                                                                                                                                | No     |
| **Cost per trial**                | The average amount you pay per trial started. <br/>**Formula**: `Spend / Count trial started`                                                                                                                                                                                                                                                                                                                                                   | No     |
| **Cost per subscription**         | The average amount you pay per subscription product purchased. <br/>**Formula**: `Spend / Count subscription started`                                                                                                                                                                                                                                                                                                                           | No     |
| **Count subscription events**     | The group of metrics for counting subscription-related events over the reporting period. The metrics are: <br/>- Count subscription started<br/>-Count subscription renewed<br/>-Count subscription renewal cancelled<br/>-Count subscription renewal reactivated<br/>-Count subscription expired<br/>-Count [subscription deferred](https://adapty.io/glossary/subscription-purchase-deferral/)<br/>-Count subscription refunded               | Yes    |
| **Count trial events**            | The group of metrics for counting trial-related events over the reporting period. The metrics are: <br/>- Count trial started<br/>- Count trial converted<br/>- Count trial expired<br/>- Count trial renewal reactivated                                                                                                                                                                                                                       | Yes    |
| **Count billing issue detected**  | The number of billing problems detected with the reported period.                                                                                                                                                                                                                                                                                                                                                                               | Yes    |
| **Count entered grace period**    | The number of subscriptions that entered a grace period due to billing issues.                                                                                                                                                                                                                                                                                                                                                                  | Yes    |
| **Count non-subscription events** | The group of metrics for counting non-subscription-related events over the reporting period. The metrics are: <br/>- Count non-subscription purchased<br/>-Count non-subscription refunded                                                                                                                                                                                                                                                      | Yes    |
| **Subscription events rate**      | Metrics showing the rate of subscription-related events relative to app installs during the reporting period. The metrics are: <br/>- Rate subscription started<br/>-Rate subscription renewed<br/>-Rate subscription renewal cancelled<br/>-Rate subscription renewal reactivated<br/>-Rate subscription expired<br/>-Rate [subscription deferred](https://adapty.io/glossary/subscription-purchase-deferral/)<br/>-Rate subscription refunded | Yes    |
| **Trial events rate**             | Metrics showing the rate of trial-related events relative to app installs during the reporting period. The metrics are: <br/>- Rate trial started<br/>- Rate trial converted<br/>- Rate trial expired<br/>- Rate trial renewal reactivated                                                                                                                                                                                                      | Yes    |
| **Rate billing issue detected**   | The rate of billing problems relative to app installs during the reporting period.                                                                                                                                                                                                                                                                                                                                                              | Yes    |
| **Rate entered grace period**     | The rate of subscriptions that entered a grace period relative to app installs during the reporting period.                                                                                                                                                                                                                                                                                                                                     | Yes    |
| **Non-subscription events rate**  | Metrics showing the rate of non-subscription-related events relative to app installs during the reporting period. The metrics are: <br/>- Rate non-subscription purchased<br/>-Rate non-subscription refunded                                                                                                                                                                                                                                   | Yes    |