openapi: 3.1.0
info:
  title: Developer API
  version: 1.0.0
servers:
  - url: https://api.adapty.io
    description: Production server
paths: {}
components:
  securitySchemes:
    apikeyAuth:
      type: apiKey
      in: header
      name: Authorization
